# generated by datamodel-codegen:
#   filename:  openapi.yaml

from enum import Enum, IntEnum
from typing import Annotated, Literal

from pydantic import BaseModel as _BaseModel
from pydantic import ConfigDict, Field, RootModel


class BaseModel(_BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class GameState(IntEnum):
    """
    Current state of the game. Not all states are used in all CTFs.
    """

    stopped = 1
    paused = 2
    running = 3


class CheckerStatus(str, Enum):
    """
    Checker status of a service for one team and round: the gameserver's verdict over
    all checker tasks of that round, derived from the CheckerTaskResult values
    (OK / MUMBLE / OFFLINE / INTERNAL_ERROR) the checker returned for each of them.
    - SUCCESS: every task returned OK
    - RECOVERING: this round's tasks are fine, but a task for an earlier round did not
      return OK - the service works, old flags are not retrievable
    - MUMBLE: a task of this round returned MUMBLE
    - OFFLINE: a task of this round returned OFFLINE
    - TIMEOUT: a task did not answer within its timeout (INTERNAL_ERROR, "TIMEOUT")
    - CRASHED: a task failed with INTERNAL_ERROR for any other reason
    - REVOKED: the one value that never comes from a checker - no result exists,
      because the task was cancelled when the round ended or answered too late.
      A task still in flight when its round is collected is revoked as well, so a
      round's statuses are final once it is scored.

    """

    success = "SUCCESS"
    recovering = "RECOVERING"
    mumble = "MUMBLE"
    offline = "OFFLINE"
    timeout = "TIMEOUT"
    crashed = "CRASHED"
    revoked = "REVOKED"


class ScoreboardCurrent(BaseModel):
    """
    API result for /api/scoreboard_current.json
    """

    model_config = ConfigDict(
        extra="allow",
    )
    current_round: Annotated[
        int,
        Field(
            description="The round we're currently playing (if live), 0 before the game, last played round after the game."
        ),
    ] = 0
    state: Annotated[
        GameState,
        Field(description="Current state of the game (running / stopped / paused)"),
    ]
    validity_period: Annotated[
        int,
        Field(
            description="number of rounds that the flags are valid for (in addition to the round they're stored in)"
        ),
    ]
    current_round_start: Annotated[
        int | None, Field(description="Unix timestamp when the current round started")
    ] = None
    current_round_until: Annotated[
        int | None,
        Field(description="Unix timestamp when the current round ends/ended"),
    ] = None
    scoreboard_round: Annotated[
        int,
        Field(
            description="Round number until which the scoreboard is created (per-round urls are available).\n-1 is a valid round where the game hasn't started yet and the service names are hidden.\n"
        ),
    ] = -1
    banned_teams: Annotated[
        list[int],
        Field(
            description="List of team IDs that are cut off from network, or permanently banned"
        ),
    ] = []
    frozen: Annotated[
        bool,
        Field(
            description="true if the scoreboard is frozen (scores not updated in final moments of the game)"
        ),
    ] = False


class TeamServiceRoundInfo(BaseModel):
    """
    Scores for one service for one team (one cell in the main scoreboard table)
    """

    offense_points: Annotated[
        float, Field(alias="o", description="Offense points, total")
    ]
    defense_points: Annotated[
        float, Field(alias="d", description="Defense points, total")
    ]
    sla_points: Annotated[float, Field(alias="s", description="SLA points, total")]
    offense_points_delta: Annotated[
        float,
        Field(
            alias="do",
            description="Difference in offense points compared to previous round",
        ),
    ]
    defense_points_delta: Annotated[
        float,
        Field(
            alias="dd", description="Difference in defense compared to previous round"
        ),
    ]
    sla_points_delta: Annotated[
        float,
        Field(alias="ds", description="Difference in SLA compared to previous round"),
    ]
    stolen_flags: Annotated[
        int,
        Field(
            alias="st",
            description="Number of flags stolen from this team (this team is the victim)",
        ),
    ]
    captured_flags: Annotated[
        int,
        Field(
            alias="cap",
            description="Number of flags captured by this team (this team is the attacker)",
        ),
    ]
    stolen_flags_delta: Annotated[
        int,
        Field(
            alias="dst",
            description="Difference in stolen flags compared to previous round (this team is the victim)",
        ),
    ]
    captured_flags_delta: Annotated[
        int,
        Field(
            alias="dcap",
            description="Difference in captured flags compared to previous round (this team is the attacker)",
        ),
    ]
    checker_status: Annotated[
        CheckerStatus, Field(alias="c", description="Checker status in this round")
    ]
    checker_message: Annotated[
        str | None,
        Field(
            alias="m",
            description="Additional message from the checker, if any. Can be empty or null if missing.\n",
        ),
    ]
    checker_status_history: Annotated[
        list[CheckerStatus],
        Field(
            alias="dc",
            description="Checker status in the past N rounds. Order: newest first. [result X-1, result X-2, ...]",
        ),
    ]


class ScoreboardTeamRow(BaseModel):
    """
    The per-round stats of one team (single row in the scoreboard table)
    """

    team_id: Annotated[int, Field(description="ID of the team")]
    rank: Annotated[
        int,
        Field(
            description="Current rank of the team (1 is the winning team, ranks might or might not be not unique if teams have the same score)"
        ),
    ]
    points: Annotated[float, Field(description="Total points for the team")]
    services: Annotated[
        list[TeamServiceRoundInfo],
        Field(description="Scores for each service for this team"),
    ]
    offense_points: Annotated[
        float, Field(alias="o", description="Total/overall offense points")
    ]
    defense_points: Annotated[
        float, Field(alias="d", description="Total/overall defense points")
    ]
    sla_points: Annotated[
        float, Field(alias="s", description="Total/overall SLA points")
    ]
    offense_points_delta: Annotated[
        float,
        Field(
            alias="do",
            description="Total offense points compared to last round (delta)",
        ),
    ]
    defense_points_delta: Annotated[
        float,
        Field(
            alias="dd",
            description="Total defense points compared to last round (delta)",
        ),
    ]
    sla_points_delta: Annotated[
        float,
        Field(
            alias="ds", description="Total SLA points compared to last round (delta)"
        ),
    ]


class FirstBlood(BaseModel):
    name: Annotated[
        str | None, Field(description="Name of the team that achieved first blood")
    ] = None
    ts: Annotated[
        float | None, Field(description="Unix timestamp of the first blood submission")
    ] = None
    confirmed: Annotated[
        bool | None,
        Field(
            description="True if we consider this a valid first blood (if relevant for game definition)"
        ),
    ] = None
    level: Annotated[
        int | None,
        Field(
            description="Firstblood level achieved (if supported by game definition)"
        ),
    ] = None
    payload: Annotated[
        int | None,
        Field(description="Payload / flag store index this first blood was scored on"),
    ] = None


class ServiceRoundInfo(BaseModel):
    """
    Status of one service for one round (in scoreboard table: header cell with service name)
    """

    name: Annotated[str, Field(description="Name of the service")]
    attackers: Annotated[
        int | Literal["?"],
        Field(
            description='Number of teams that successfully stole at least one flag in this round, or "?" if hidden'
        ),
    ]
    victims: Annotated[
        int | Literal["?"],
        Field(
            description='Number of teams that were successfully attacked on this service in this round, or "?" if hidden'
        ),
    ]
    first_blood: Annotated[
        list[FirstBlood],
        Field(
            description="List of teams that achieved first blood on a flag store of this service. One entry per first-blooded flagstore.",
            validate_default=True,
        ),
    ] = []
    flag_stores: Annotated[
        int, Field(description="Total number of flag stores for this service")
    ]
    flag_stores_exploited: Annotated[
        int,
        Field(description="Number of flag stores that have already been first-blooded"),
    ]


class ScoreboardRound(BaseModel):
    """
    API result for /api/scoreboard_round_{round}.json
    """

    round: Annotated[
        int,
        Field(
            description="Round number (as in request). \nData for round 1 is created AFTER round 1 finished (while round 2 is running).\nRound -1 is before the game starts (service names hidden).\nRound 0 is when the game starts but no round has completed (service names revealed).\n"
        ),
    ]
    scoreboard: Annotated[
        list[ScoreboardTeamRow],
        Field(
            description="A list of all teams, ordered by score descending (like the scoreboard table)"
        ),
    ]
    services: Annotated[
        list[ServiceRoundInfo], Field(description="List of all played services")
    ]


class ScoreboardTeamHistory(BaseModel):
    """
    API result for /api/scoreboard_team_{team_id}.json
    """

    services: Annotated[list[str], Field(description="Ordered list of all services")]
    points: Annotated[
        list[list[float]],
        Field(
            description="Points per service, items in same order as services (points[i][round] belongs to services[i])"
        ),
    ]


class StaticTeamInfo(BaseModel):
    """
    Static information about one team.
    """

    name: Annotated[str, Field(description="Name of the team", examples=[["NOP"]])]
    vulnbox: Annotated[
        str,
        Field(description="IP address of the team's vulnbox", examples=[["10.32.1.2"]]),
    ]
    aff: Annotated[
        str, Field(description="Team affiliation or organization (if given)")
    ]
    web: Annotated[str, Field(description="Team website URL (if given)")]
    logo: Annotated[
        str | Literal[False],
        Field(
            description="Filename of the team's logo image, without path or url. \nUsually you can fetch it from /logos/<filename> (NOT /api/logos/...). \nIf the logo is not set, this might be the filename of a placeholder image, or false.\n"
        ),
    ]


class ScoreboardTeams(RootModel[dict[str, StaticTeamInfo]]):
    """
    Information about all teams, indexed by team ID.
    API result for /api/scoreboard_teams.json

    """

    root: dict[str, StaticTeamInfo]


class ServiceAttackerVictimCount(BaseModel):
    """
    Number of attackers/victims in one round and service
    """

    num_attackers: Annotated[
        int | Literal["?"],
        Field(
            alias="a",
            description='Number of attacking teams in this round and service, or "?" if hidden',
        ),
    ]
    num_victims: Annotated[
        int | Literal["?"],
        Field(
            alias="v",
            description='Number of victim teams in this round and service, or "?" if hidden',
        ),
    ]


class ScoreboardServiceStats(BaseModel):
    """
    Number of attackers/victims per service over time.
    API result for /api/scoreboard_service_stats.json

    """

    services: Annotated[
        list[str], Field(description="List of services we have stats for")
    ]
    stats: Annotated[
        list[list[ServiceAttackerVictimCount]],
        Field(
            description="List of attacker/victim timeline per service, same length and order as services.\nstats[i][round] belongs to services[i].\n"
        ),
    ]


class AttackInfoTeam(BaseModel):
    """
    One attackable team.
    """

    id: Annotated[int, Field(description="ID of the team")]
    name: Annotated[str, Field(description="Name of the team")]
    ip: Annotated[
        str,
        Field(description="IP address of the team's vulnbox", examples=[["10.32.1.2"]]),
    ]


class AttackInfo(BaseModel):
    """
    Flag format, teams and attack info for the current round.
    API result for /api/attack.json

    """

    flag_regex: Annotated[
        str,
        Field(
            description="Regular expression that matches a flag, to find flags in exploit output"
        ),
    ]
    teams: Annotated[
        list[AttackInfoTeam],
        Field(description="List of all teams that can be attacked"),
    ]
    attack_info: Annotated[
        dict[str, dict[str, dict[str, dict[str, str | None]]]],
        Field(
            description="Attack info, keyed by service name, then by vulnbox IP, then by round.\nOnly services that publish attack info are listed.\nRounds range over the still-valid ones, excluding the current round -\nits attack info is published once the round is over.\n",
            title="AttackInfoPerService",
        ),
    ]
    current_round: Annotated[
        int,
        Field(
            description="The round we're currently playing (if live), 0 before the game, last played round after the game."
        ),
    ]
    current_round_start: Annotated[
        int | None, Field(description="Unix timestamp when the current round started")
    ]
    current_round_until: Annotated[
        int | None,
        Field(description="Unix timestamp when the current round ends/ended"),
    ]
