"""
Parsers converting raw ECSC scoreboard JSON into the models in :mod:`ecsc2026ad.models`.

attack.json is not parsed here -- ctf-attackapi's ``atklab`` dialect decodes it.

Each parser first validates the raw bytes against the pydantic models in
:mod:`ecsc2026ad.api_models` (generated by ``./schema-to-pydantic.sh`` from ``openapi.yaml``,
the gameserver's own schema), then adapts the validated result into this package's
friendlier, richer dataclasses.
"""

from typing import Dict, List

from ecsc2026ad import api_models as am
from ecsc2026ad.models import (
    FirstBlood,
    GameState,
    GameStateEnum,
    Scoreboard,
    ScoreboardTeam,
    ServiceInfo,
    ServiceResult,
    ServiceStat,
    ServiceStats,
    TeamHistory,
    TeamRanking,
)


def parse_game_state(raw: bytes) -> GameState:
    """Parse ``scoreboard_current.json`` into a :class:`GameState`."""
    parsed = am.ScoreboardCurrent.model_validate_json(raw)
    return GameState(
        current_round=parsed.current_round,
        state=GameStateEnum(parsed.state.value),
        scoreboard_round=parsed.scoreboard_round,
        current_round_start=parsed.current_round_start,
        current_round_until=parsed.current_round_until,
        validity_period=parsed.validity_period,
        banned_teams=list(parsed.banned_teams or []),
        frozen=bool(parsed.frozen),
        raw=raw,
    )


def parse_scoreboard(raw: bytes) -> Scoreboard:
    """Parse ``scoreboard_round_<round>.json`` into a :class:`Scoreboard`."""
    parsed = am.ScoreboardRound.model_validate_json(raw)

    services = [
        ServiceInfo(
            name=service.name,
            attackers=service.attackers,
            victims=service.victims,
            first_blood=[
                # the schema marks none of these required, so fall back rather than
                # drop a first blood the gameserver did report
                FirstBlood(
                    name=fb.name or "",
                    ts=fb.ts or 0.0,
                    confirmed=bool(fb.confirmed),
                    level=fb.level or 0,
                    payload=fb.payload,
                )
                for fb in (service.first_blood or [])
            ],
            flag_stores=service.flag_stores,
            flag_stores_exploited=service.flag_stores_exploited,
        )
        for service in (parsed.services or [])
    ]

    ranking: List[TeamRanking] = []
    for row in parsed.scoreboard or []:
        results = [
            ServiceResult(
                off_points=sr.offense_points,
                def_points=sr.defense_points,
                sla_points=sr.sla_points,
                delta_off=sr.offense_points_delta,
                delta_def=sr.defense_points_delta,
                delta_sla=sr.sla_points_delta,
                stolen=sr.stolen_flags,
                captured=sr.captured_flags,
                delta_stolen=sr.stolen_flags_delta,
                delta_captured=sr.captured_flags_delta,
                checker_status=sr.checker_status.value,
                checker_message=sr.checker_message,
                previous_checker_status=[
                    status.value for status in (sr.checker_status_history or [])
                ],
            )
            for sr in (row.services or [])
        ]
        ranking.append(
            TeamRanking(
                team_id=row.team_id,
                rank=row.rank,
                points=row.points,
                off_points=row.offense_points,
                def_points=row.defense_points,
                sla_points=row.sla_points,
                delta_off=row.offense_points_delta,
                delta_def=row.defense_points_delta,
                delta_sla=row.sla_points_delta,
                services=results,
            )
        )

    return Scoreboard(round=parsed.round, services=services, ranking=ranking, raw=raw)


def parse_scoreboard_teams(raw: bytes) -> Dict[int, ScoreboardTeam]:
    """Parse ``scoreboard_teams.json`` into ``{team_id: ScoreboardTeam}``."""
    parsed = am.ScoreboardTeams.model_validate_json(raw)
    result: Dict[int, ScoreboardTeam] = {}
    for team_id, entry in parsed.root.items():
        tid = int(team_id)
        result[tid] = ScoreboardTeam(
            id=tid,
            name=entry.name or "",
            vulnbox=entry.vulnbox or "",
            affiliation=entry.aff or "",
            website=entry.web or "",
            logo=entry.logo if entry.logo is not None else False,
        )
    return result


def parse_team_history(raw: bytes) -> TeamHistory:
    """Parse ``scoreboard_team_<id>.json`` into a :class:`TeamHistory`."""
    parsed = am.ScoreboardTeamHistory.model_validate_json(raw)
    return TeamHistory(
        services=list(parsed.services or []),
        points=[list(row) for row in (parsed.points or [])],
    )


def parse_service_stats(raw: bytes) -> ServiceStats:
    """Parse ``scoreboard_service_stats.json`` into a :class:`ServiceStats`."""
    parsed = am.ScoreboardServiceStats.model_validate_json(raw)
    stats = [
        [
            ServiceStat(attackers=cell.num_attackers, victims=cell.num_victims)
            for cell in row
        ]
        for row in (parsed.stats or [])
    ]
    return ServiceStats(services=list(parsed.services or []), stats=stats)
